.PHONY: all release clean debug

all : release

release:
	@make release -C liblodepng
	@make release -C flann
	@make release -C libadjuster
	@make release -C libblend
	@make release -C libcamera
	@make release -C libcolor
	@make release -C libconfig
	@make release -C libdist
	@make release -C libfeature
	@make release -C libhomography
	@make release -C libimg
	@make release -C libkdtree
	@make release -C libmat
	@make release -C libpolygon
	@make release -C libtransform
	@make release -C libwarp
	@make release -C libplanedrawer
	@make release -C libmatch
	@make release -C libstitch
	@make release -C liblut
	@make release -C libstitchout
	
debug:
	@make debug -C liblodepng
	@make debug -C flann
	@make debug -C libadjuster
	@make debug -C libblend
	@make debug -C libcamera
	@make debug -C libcolor
	@make debug -C libconfig
	@make debug -C libdist
	@make debug -C libfeature
	@make debug -C libhomography
	@make debug -C libimg
	@make debug -C libkdtree
	@make debug -C libmat
	@make debug -C libpolygon
	@make debug -C libtransform
	@make debug -C libwarp
	@make debug -C libplanedrawer
	@make debug -C libmatch
	@make debug -C libstitch
	@make debug -C liblut
	@make debug -C libstitchout

clean:
	@make clean -C liblodepng
	@make clean -C flann
	@make clean -C libadjuster
	@make clean -C libblend
	@make clean -C libcamera
	@make clean -C libcolor
	@make clean -C libconfig
	@make clean -C libdist
	@make clean -C libfeature
	@make clean -C libhomography
	@make clean -C libimg
	@make clean -C libkdtree
	@make clean -C libmat
	@make clean -C libpolygon
	@make clean -C libtransform
	@make clean -C libwarp
	@make clean -C libmatch
	@make clean -C libplanedrawer
	@make clean -C libstitch
	@make clean -C liblut
	@make clean -C libstitchout
